### ISSUE TITLE
Revoke token does not work

### ISSUE THREAD

**Issue by bzq360** [onelogin/onelogin-oidc-android#10]
Device: Samsung A52
Android version: 11

I implemented `revokeToken` method as suggested in the demo and received a `onSuccess` callback. But I can still login successfully without re-input account and password, which implies that `logout` failed. Then I found a revoke token endpoint and a logout endpoint from the onelogin doc. What is the difference between those two endpoints and this `revokeToken` method? Is it possible to handle `logout` on the Android device without talking to the backend?

revoke token endpoint: https://developers.onelogin.com/openid-connect/api/revoke-token
logout endpoint: https://developers.onelogin.com/openid-connect/api/logout

**Comment by WPSeven** [comment]
Hi @bzq360 
I also facing the same issue.
Did you get the solution to logout on the Android device without talking to the backend?

**Comment by WPSeven** [comment]
Now I found the Merge Request
[Merge pull request](https://github.com/onelogin/onelogin-oidc-android/commit/941e048c55a0dd834bd2ddadf64dbeb536dcf68c) https://github.com/onelogin/onelogin-oidc-android/pull/12 [from onelogin/add_signout_route](https://github.com/onelogin/onelogin-oidc-android/commit/941e048c55a0dd834bd2ddadf64dbeb536dcf68c)
